name: StarvalCityScript
authors: [Nirflection, Donaris, Stormy_The_Fox, sYnTaX]
main: de.starvalcity.system.corepackage.Core
version: ${project.version}
api-version: 1.16
softdepend:
  - LuckPerms
description: StarvalCity ServerScript

commands:
  ip:
    description: Displays an IP address of a specific player
    usage: /ip [Player]
  onlineplayers:
    description: Displays all current online players
    usage: /onlineplayers
  staff:
    description: Joins or leaves the Staff-Mode
    usage: /staff

permissions:
  ip.own:
    description: Allows viewing own IP address
    default: op
  ip.other:
    description: Allows viewing other IP addresses
    default: op
  onlineplayers.use:
    description: General onlineplayers permission
    default: op
  staffmode.use:
    description: General Staff-Mode permission
    default: op