name: StarvalCityScript
authors: [Nirflection, Donaris, Stormy_The_Fox, sYnTaX]
main: de.starvalcity.system.basepackage.Core
version: 1.0.0
api-version: 1.13
description: StarvalCity ServerScript

commands:
  language:
    aliases:
      - langset
      - languageset
      - setlanguage
      - setlang
    description: Sets the language
    usage: /language