name: StarvalCityScript
authors: [Nirflection, Donaris, Stormy_The_Fox, sYnTaX]
main: de.starvalcity.system.corepackage.Core
version: ${project.version}
api-version: 1.16
softdepend:
  - LuckPerms
description: StarvalCity ServerScript

commands:
  staff:
    description: Joins or leaves the Staff-Mode
    usage: /staff

permissions:
  staffmode.use:
    description: General Staff-Mode permission
    default: op