name: StarvalCityScript
authors: [Nirflection, Donaris, Stormy_The_Fox, sYnTaX]
main: de.starvalcity.system.basepackage.Core
version: 1.0.0
api-version: 1.13
description: StarvalCity ServerScript

commands:
  language:
    description: Language command
    usage: /language <info; set>
  staff:
    description: Staff command
    usage: /staff <info; join; leave>

permissions:
  language.*:
    description: Admin permission for language command
    default: op
    children:
      language.info: true
      language.set: true
  language.info:
    description: Shows the current client language
    default: op
  language set:
    description: Sets the client language
    default: op
  staff.*:
    description: Admin permission for staff command
    default: op
    children:
      staff.general: true
      staff.info: true
      staff.join: true
      staff.leave: true
  staff.general:
    description: General permission for staff command
    default: op
  staff.info:
    description: Shows all current staff members
    default: op
  staff.join:
    description: Sets oneself in staff mode
    default: op
  staff.leave:
    description: Removes oneself from staff mode
    default: op