name: StarvalCityScript
authors: [Nirflection, Donaris, Stormy_The_Fox, sYnTaX]
main: de.starvalcity.system.basepackage.Core
version: 1.0.0
api-version: 1.13
description: StarvalCity ServerScript

commands:
  language:
    description: Language command
    usage: /language <info; set>

permissions:
  language.*:
    description: Admin permission for language command
    default: op
    children:
      - language.info
      - language.set