name: StarvalCityScript
authors: [Nirflection, Donaris, Stormy_The_Fox, sYnTaX]
main: de.starvalcity.system.corepackage.Core
version: 1.0.0
api-version: 1.16
softdepend:
  - LuckPerms
description: StarvalCity ServerScript

commands:
  language:
    description: Changes the language
    usage: /language <en; de>

permissions:
  ip.own:
    description: Allows viewing own IP address
    default: op
  ip.other:
    description: Allows viewing other IP addresses
    default: op
  language.use:
    description: General language permission
    default: op
  onlineplayers.use:
    description: General onlineplayers permission
    default: op
  staffmode.use:
    description: General Staff-Mode permission
    default: op